### ISSUE TITLE
Integrar com o Call4Papers

### ISSUE THREAD

**Issue by jesuino** [Jug-Vale/SorteaProjeto#1]
Permitir buscar os inscritos que compareceram a um determinado evento do call4papers para sortear.

http://call4papers-jugvale.rhcloud.com/rest/evento/{ID Evento}/inscritos

O endpoint acima pode ser usado. Embora ele esteja "cagado", pois traz muita info, pode ser usado facilmente.

O que deve ser feito é a request HTTP para o call4papers e trazer a lista de inscritos, filtrar os que compareceram e atribuir a essa lista:

https://github.com/Jug-Vale/SorteaProjeto/blob/master/src/SorteaProjeto.java#L46

Um botão novo poderá ser adicionado para fazer isso. Importante é marcar os presentes como inscritos ao chegarem no evento ou vai faltar gente!

**Comment by pedro-hos** [comment]
Estava pensando em fazer um endpoint pegaParticipantesNoUltimoEvento kkkk mas rola pegar esse endpoint e tratar. Vou puxar uma branch em breve :dancers: Para terminar até sábado kkkkk

**Comment by jesuino** [comment]
husahusa exato e pra não quebrar o que está funcionando, depois a gente abre um enhancement.

Pra fazer request HTTP do JavaFX, use async, ou ele trava a thread de desenho da tela. Dá um bizu aqui -> http://aprendendo-javafx.blogspot.com.br/2014/08/threads-e-javafx.html

eu recomendo também usar um cliente JAX-RS 2.0, como o Resteasy client, aí nem parsing vamos precisar fazer e pegar o JSON prontinho

**Comment by pedro-hos** [comment]
@jesuino dei o start nessa issue 😄 usei como exemplo: https://github.com/jesuino/rfid-javafx/blob/master/client-module/src/main/java/org/jugvale/peoplemanagement/client/service/RESTPersonService.java

**Comment by jesuino** [comment]
Integração feita com sucesso :-)

**Comment by pedro-hos** [comment]
\o yeah
